dist: xenial
language: ruby
gemfile: ci/Gemfile
env:
  - ACTIVE_SUPPORT=true
  - NO_ACTIVE_SUPPORT=true
rvm:
  - 2.3.8
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - ruby-head
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
before_install:
   - gem install bundler -v '~> 1.17'
